In [1]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('task1_vgg2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
        name="None matching"
        
        if(pred[0][0]):
            name='Deepa'
        elif(pred[0][1]):
            name='Sami'
        elif(pred[0][2]):
            name='Siddharth'
            
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1)==13:
        video_capture.release()
        cv2.destroyAllWindows()

Using TensorFlow backend.


[[0.         0.8538099  0.14619006]]
[[0.000000e+00 1.000000e+00 4.390157e-10]]
[[0.000000e+00 2.233514e-10 1.000000e+00]]
[[0.0000000e+00 1.5767664e-04 9.9984229e-01]]
[[0.000000e+00 9.233930e-08 9.999999e-01]]
[[0.000000e+00 4.619557e-25 1.000000e+00]]
[[0.0000000e+00 5.2009716e-07 9.9999952e-01]]
[[0.0000000e+00 1.2220674e-12 1.0000000e+00]]
[[0.0000000e+00 2.2132704e-16 1.0000000e+00]]
[[0.0000000e+00 1.3909859e-31 1.0000000e+00]]
[[0.0000000e+00 3.6072567e-15 1.0000000e+00]]
[[0.000000e+00 1.822591e-20 1.000000e+00]]
[[0.0000000e+00 1.8978408e-37 1.0000000e+00]]
[[0.0000000e+00 3.1856052e-14 1.0000000e+00]]
[[0.000000e+00 7.652889e-16 1.000000e+00]]
[[0.0000000e+00 2.3073291e-14 1.0000000e+00]]
[[0.0000000e+00 3.0407256e-20 1.0000000e+00]]
[[0. 0. 1.]]
[[0.000000e+00 1.000000e+00 5.502472e-13]]
[[0.000000e+00 9.999651e-01 3.492743e-05]]
[[0.0000000e+00 1.0000000e+00 1.8284857e-09]]
[[0. 0. 1.]]
[[0.0000000e+00 1.6429828e-30 1.0000000e+00]]
[[0.000000e+00 3.024792e-37 1.000000e+00]

error: OpenCV(3.4.2) C:\Miniconda3\conda-bld\opencv-suite_1534379934306\work\modules\highgui\src\window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
